# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_signup_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='doner_kebab',
            field=models.CharField(default='kosher', max_length=3),
            preserve_default=False,
        ),
    ]
